version: '2'
services:
  jeecg-boot-mysql:
    build:
      context: ./jeecg-boot/db
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
    restart: always
    container_name: jeecg-boot-mysql
    image: jeecg-boot-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql

  jeecg-boot-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    container_name: jeecg-boot-redis
    command: redis-server --requirepass "p@ssw0rd"

  jeecg-boot-system:
    build:
      context: ./jeecg-boot/jeecg-boot-module-system
    restart: always
    container_name: jeecg-boot-system
    image: jeecg-boot-system
    ports:
      - 8080:8080

  jeecg-ui:
    image: nginx:jeecgboot
    ports:
      - 80:80
    container_name: jeecg-ui
    restart: always
